project:
  type: website
  output-dir: docs
execute:
  freeze: true
website:
  google-analytics: "G-XNZGT59XWP"
  title: "Te Fiti"
  favicon: favicon/android-chrome-512x512.png
  open-graph:
    locale: en_US
  twitter-card:
    image: street.jpg
    card-style: summary
    creator: "@tefiti"
  site-url: https://tefitidotai.github.io/website/
  description: "Blog for machine learning, programming, computer science and other data science related topics"
  navbar:
    right:
      - text: "Home"
        file: blog.qmd
home: blog.qmd
page-footer: 
  left: "Te Fiti" 
  right: 
    - icon: linkedin
      text: LinkedIn
      href: "#"
    - icon: github
      text: Github
      href: "#"
    - icon: twitter
      text: Twitter
      href: "#"
    - icon: rss
      text: Blog RSS
      href: blog.xml
    - icon: rss
      text: TIL RSS
      href: til.xml
format:
  html:
    css: styles.css
    theme: 
      light: cosmo
      dark: cyborg


